[package]
authors = ["EFanZh <efanzh@gmail.com>"]
categories = ["compilers"]
description = "Parses mangled names and produces structured results."
edition = "2018"
keywords = ["demangle"]
license = "MIT"
name = "ast-demangle"
repository = "https://github.com/EFanZh/ast-demangle"
version = "0.1.0"

[dependencies]
nom = "6"
punycode = "0.4"

[dev-dependencies]
rustc-demangle = "*"

[workspace]
members = ["tools/verify-against-rustc-demangle"]
