[package]
authors = ["EFanZh <efanzh@gmail.com>"]
categories = ["compilers"]
description = "Parses mangled names and produces structured results."
edition = "2021"
keywords = ["demangle"]
license = "MIT"
name = "ast-demangle"
repository = "https://github.com/EFanZh/ast-demangle"
version = "0.2.0"

[dependencies]
num-traits = "0.2"
punycode = "0.4"

[dev-dependencies]
rustc-demangle = "0.1"
